const ALLOW_HEADERS: &'static [&'static str] = &[
    "accept-encoding",
    "accept-language",
    "accept",
    "access-control-allow-origin",
    "authorization",
    "cache-control",
    "connection",
    "content-length",
    "content-type",
    "dnt",
    "git-protocol",
    "pragma",
    "range",
    "referer",
    "user-agent",
    "x-authorization",
    "x-http-method-override",
    "x-requested-with",
];

const EXPOSE_HEADERS: &'static [&'static str] = &[
    "accept-ranges",
    "age",
    "cache-control",
    "content-length",
    "content-language",
    "content-type",
    "date",
    "etag",
    "expires",
    "last-modified",
    "location",
    "pragma",
    "server",
    "transfer-encoding",
    "vary",
    "x-github-request-id",
    "x-redirected-url",
];

const ALLOW_METHODS: &'static [&'static str] = &[
    "POST",
    "GET",
    "OPTIONS",
];
